version: '3'

services: 
    app:
        image: "jksantos/php${PHP_VERSION}:latest"
        entrypoint: dockerize -wait tcp://mysql:3306 -timeout 40s php-fpm
        container_name: app
        networks: 
            - api-network
        volumes: 
            - .:/var/www
        depends_on: 
            - mysql
        
    mysql:
        image: "jksantos/mysql${MYSQL_VERSION}:latest"
        container_name: mysql
        networks: 
            - api-network
        ports: 
            - "3306:3306"
        command: --innodb-use-native-aio=0
        volumes: 
            - .docker/mysql/dbdata:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=baseapp
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root

    nginx:
        image: "jksantos/nginx${NGINX_VERSION}:latest"
        container_name: nginx
        entrypoint: dockerize -template ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf nginx -g "daemon off;"
        restart: always
        tty: true
        ports: 
            - "8000:80"
        networks: 
            - api-network
        volumes: 
            - .:/var/www
        environment: 
            - HOST_APP=app
            - PORT_APP=9000
        depends_on: 
            - app

    redis:
        image: redis:4-alpine
        ports:
            - 6379:6379
        networks:
            - api-network

networks: 
    api-network:
        driver: bridge