version: '3'

services: 
    app:
        image: jksantos/php:7.2.19-fpm-alpine3.10
        build: .docker/PHP
        entrypoint: dockerize -wait tcp://mysql:3306 -timeout 40s php-fpm
        container_name: app
        networks: 
            - api-network
        volumes: 
            - .:/var/www
        depends_on: 
            - mysql
        
    mysql:
        build: .docker/mysql
        image: jksantos/mysql:5.7
        container_name: mysql
        networks: 
            - api-network
        ports: 
            - "3306:3306"
        command: --innodb-use-native-aio=0
        volumes: 
            - .docker/mysql/dbdata:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=webcvtenants
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root

    nginx:
        build: .docker/nginx
        image: jksantos/nginx:1.17.9-alpine
        container_name: nginx
        entrypoint: dockerize -template ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf nginx -g "daemon off;"
        restart: always
        tty: true
        ports: 
            - "8000:80"
        networks: 
            - api-network
        volumes: 
            - .:/var/www
        environment: 
            - HOST_APP=app
            - PORT_APP=9000
        depends_on: 
            - app

networks: 
    api-network:
        driver: bridge