version: "3.7"
services:
  app:
    build:
      args:
        user: vscode
        uid: 1000
      context: ../.docker/app/
      dockerfile: Dockerfile
    image: php
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www
      - /home/${USER}/.ssh:/home/vscode/.ssh:ro
    networks:
      - app-network

  db:
    image: mysql:8.0.30
    container_name: db
    restart: unless-stopped
    command: mysqld --sql_mode=""
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: novaera
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: novaera
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ../.docker/mysql:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www
      - ../.docker/nginx/conf.d:/etc/nginx/conf.d
      - ../.docker/nginx/logs:/var/log/nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
