name: Deploy
on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:

        - uses: actions/checkout@v2

        - name: Docker meta
          id: docker_meta
          uses: crazy-max/ghaction-docker-meta@v1
          with:
            images: jksantos/php7.2.19
            tag-sha: true

        - name: Get DotEnv
          id: dotenv
          uses: falti/dotenv-action@v0.2.5
          
        - name: QEMU
          uses: docker/setup-qemu-action@v1

        - name: Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to Dockerhub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME}}
            password: ${{ secrets.DOCKERHUB_TOKEN}}

        - name: Bump version and push tag
          id: tagging
          uses: mathieudutour/github-tag-action@v4.5
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push PHP
          id: docker_build_php
          uses: docker/build-push-action@v2
          with:
            push: true
            context: .docker/PHP/
            file: .docker/PHP/Dockerfile
            tags: jksantos/php${{ steps.dotenv.outputs.php_version }}:latest,jksantos/php${{ steps.dotenv.outputs.php_version }}:${{ steps.tagging.outputs.new_version }}

        - name: Build and push MySql
          id: docker_build_mysql
          uses: docker/build-push-action@v2
          with:
            push: true
            context: .docker/mysql/
            file: .docker/mysql/Dockerfile
            tags: jksantos/mysql5.7:latest,jksantos/mysql5.7:${{ steps.tagging.outputs.new_version }}

        - name: Build and push Nginx
          id: docker_build_nginx
          uses: docker/build-push-action@v2
          with:
            push: true
            context: .docker/nginx/
            file: .docker/nginx/Dockerfile
            tags: jksantos/nginx1.17.9:latest,jksantos/nginx1.17.9:${{ steps.tagging.outputs.new_version }}
